### ISSUE TITLE
error running pixeltrack.py defaults.ini

### ISSUE THREAD

**Issue by willkochtitzky** [whyjz/CARST#12]
When I ran pixeltrack.py defaults.ini

I got this error message:
```
Traceback (most recent call last):
  File "./pixeltrack.py", line 91, in <module>
    idx = points_in_polygon(ampoff.data[:, [0,2]], shp)
  File "/Users/willkochtitzky/bin/GitHub/CARST/pixeltrack/../Utilities/Python/UtilXYZ.py", line 615, in points_in_polygon
    poly_geometries = [shapefile.ix[i]['geometry'] for i in range(len(shapefile))]
  File "/Users/willkochtitzky/bin/GitHub/CARST/pixeltrack/../Utilities/Python/UtilXYZ.py", line 615, in <listcomp>
    poly_geometries = [shapefile.ix[i]['geometry'] for i in range(len(shapefile))]
  File "/Users/willkochtitzky/miniconda3/envs/autoRIFT/lib/python3.7/site-packages/pandas/core/generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'GeoDataFrame' object has no attribute 'ix'
```

Do you know what could be causing it? My reading suggests this is now depreciated:https://stackoverflow.com/questions/59991397/attributeerror-dataframe-object-has-no-attribute-ix
Do you have ideas about how to get around this?

**Comment by whyjz** [comment]
Thanks for the feedback. It seems that the solution is to replace "shapefile.ix" with "shapefile.loc" at line 615 in the File UtilXYZ.py. I have updated the code and let me know if that solves the issue!
