### ISSUE TITLE
NI file does not exist, raising AttributeError.

### ISSUE THREAD

**Issue by han357** [whyjz/CARST#24]
```
u5151580@qoxbxnctr1726327013778-nzjlk:~$ dhdt.py defaults.ini
Traceback (most recent call last):
  File "/home/u5151580/.local/bin/dhdt.py", line 37, in <module>
    a.read_config(inipath)
  File "/home/u5151580/.local/lib/python3.10/site-packages/carst/libdhdt.py", line 646, in read_config
    self.picklepath = ini.result['picklefile']
AttributeError: 'ConfParams' object has no attribute 'result'
```

When the file does not exist, a raw Python error is raised, which makes it difficult for users to understand.

Need to implement a function to check if the file exists.

**Comment by whyjz** [comment]
Thanks @han357 for describing the issue! I am changing the issue title so that we can better track what's going on here.
